spring:
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    timeout: 0
#    pool:
#      max-active: 200
#      max-wait: 10000
#      max-idle: 150
#      min-idle: 50
    lock:
      waitTimeOut: 5
      lockTimeOut: 10
  session:
    timeout: 3600
    store-type: redis

  datasource:
    name: test
    url: jdbc:mysql://wpay.mega-tech.com.cn/orange?useUnicode=true&characterEncoding=UTF8&allowMultiQueries=true
    username: feichina
    password: xlgl1004
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20

server:
  port: 8089


dubbo:
  application:
    name: sfg-web-dubbo-provider
    owner: sfg-web-dubbo-provider
  registry:
    protocol: zookeeper
    address: localhost:2181
  protocol:
    name: dubbo
    port: -1

logging:
  level:
    root: info